BCYips/Models/Yip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace BCYips.Models
{
    public class Yip
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Required]
        public int YipperID { get; set; }
        [Required, ForeignKey("YipperID")]
        public virtual Yipper Yipper { get; set; }

        public Yip ReYip { get; set; }

        public Yip ReplyTo { get; set; }

        [StringLength(140)]
        public string Content { get; set; }
        
        [DataType(DataType.Date)]
        public DateTime Posted { get; set; }
    }
}

BCYips/Controllers/YipsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BCYips.Models;

namespace BCYips.Controllers
{
    public class YipsController : Controller
    {
        private YipDbContext db = new YipDbContext();

        //
        // POST: /Yips/Create

        [HttpPost]
        public ActionResult Create(Yip yip)
        {
            var yipper = db.Yippers.First(s => s.UserName == User.Identity.Name);
            yip.YipperID = yipper.ID;
            yip.Yipper = yipper;
            yip.Posted = DateTime.Now;
            ModelState.Remove("Yipper");
            var isValid = ModelState.IsValid && !string.IsNullOrWhiteSpace(yip.Content);

            if (isValid)
            {
                db.Yips.Add(yip);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            ((System.Web.Mvc.ModelState)ModelState["Content"]).Errors.Add(new ModelError("There was an error posting your yip."));
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BCYips/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - BC Yips!</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
        @RenderSection("Styles", false)
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/Scripts/jquery-1.7.1.min.js")
    </head>
    
    <body class="@HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()">
        
        <header>
            @Html.Partial("_Logo")
        </header>
        
        @if (Request.IsAuthenticated)
        {
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("home", "Index", "Home")</li>
                    <li>@Html.ActionLink("explore", "Explore", "Home")</li>
                    <li>@Html.ActionLink(User.Identity.Name + "'s profile", "Index", "Profile")</li>
                    <li>@Html.Partial("_LoginPartial")</li>
                </ul>
            </nav>
        }
        
        <article>
            <aside>
                @RenderSection("aside", required: false)
            </aside>
        
            <section>
                @RenderBody()
            </section>
        </article>

        <footer>
            &copy; @DateTime.Now.Year - Bellevue College
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

BCYips/Views/Shared/_Logo.cshtml
<a href="@Url.Action("Index", "Home") %>" class="logo-mascot" >
    <img src="~/Images/bulldog.png" alt=""/>
</a>
<a href="@Url.Action("Index", "Home") %>" class="logo-yips" >
    <img src="~/Images/yips-logo.png" alt=""/>
</a>
<a href="@Url.Action("Index", "Home") %>" class="logo-bc" >
    <img src="~/Images/bclogo.png" alt=""/>
</a>

BCYips/Views/Shared/_PostYip.cshtml
@model BCYips.Models.Yip

@using (Html.BeginForm("Create", "Yips")) {
    @Html.ValidationSummary(false)
    <script src="~/Scripts/counter.js"></script>

    <fieldset>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Content, new { placeholder = "Compose new yip...", rows = "7", maxlength = "140"})
            @Html.ValidationMessageFor(model => model.Content)
        </div>
        <p>
            <label id="char-count">140</label>
            <input class="create-yip-button" type="submit" value="Yip!" />
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BCYips/Views/Shared/_Yip.cshtml
@using BCYips.Models

<div class="yip">
    <div class="userpic"></div>
    <div class="details">
        <div class="heading">
            @if (Model.ReYip != null)
            {
                <span class="fullname">@Model.ReYip.Yipper.FirstName @Model.ReYip.Yipper.LastName</span> <span class="username">@@@Model.ReYip.Yipper.UserName</span>
            }
            else
            {
                <span class="fullname">@Model.Yipper.FirstName @Model.Yipper.LastName</span> <span class="username">@@@Model.Yipper.UserName</span>
            }
        </div>
        @if (Model.ReYip != null)
        {
            <div class="content">
                @Model.ReYip.Content
            </div>
        }
        @if (Model.ReplyTo != null)
        {
            <div class="content">
                <span class="reply-to">@@@Model.ReplyTo.Yipper.UserName</span> <span class="reply-quote">"@Model.ReplyTo.Content"</span> ... <span class="yip-content">@Model.Content</span>
            </div>
        }
        else if (!String.IsNullOrEmpty(Model.Content))
        {
            <div class="content">
                @Model.Content
            </div>
        }
        <div class="post-time">@Model.Posted</div>
    </div>
</div>

BCYips/Views/Shared/_Yips.cshtml
@using BCYips.Models

<h2>All Yips!</h2>
@foreach (var yip in Model)
{
    @Html.Partial("_Yip", (Yip) yip)
}